language:
  - generic

os:
  - linux

dist:
  - xenial

services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - pyo@robotis.com
      - thlim@robotis.com

branches:
  only:
    - main
    - develop

install:
  - git clone --quiet --depth 1 https://github.com/robotpilot/ros2ci.git .ros2ci

jobs:
  include:
    - script: .ros2ci/travis.bash foxy
